# Generated by Django 3.1.6 on 2023-04-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_catogie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogie',
            new_name='Categorie',
        ),
    ]
